### ISSUE TITLE
It does not find lyrics for some songs

### ISSUE THREAD

**Issue by khebrati** [abhishekabhi789/LyricsForPowerAmp#10]
Hi, great app!
there is an issue that on my phone ( xiaomi redmi note 13 ) with HyperOs for some songs it is totally unable  to fetch lyrics into poweramp no matter how many times tried ( but I can still search and find lyrics for it in the app itself ). Re opening the apps did not solve it.

**Comment by abhishekabhi789** [comment]
I don't fully understand your question. It sounds like the issue is with the metadata fields.

Did you edit the search parameters to get the result, or did you just proceed with the prepopulated values from PowerAmp? If you edited the metadata while searching, the issue may be related to the metadata.

OR


Sure! Here's your paragraph with improved grammar:

"I don't fully understand your question. It sounds like the issue is with the metadata fields.

Did you edit the search parameters to get the result, or did you just proceed with the prepopulated values from Poweramp? If you edited the metadata while searching, the issue may be related to the metadata. OR

Do you mean it sets lyrics for some songs but doesn't do anything for others, even though the lyrics are available for those tracks? The plugin might not be responding. It can post a notification if it fails to fetch lyrics, suggesting you perform a manual search. Check under the plugin settings and System > Apps > [this plugin’s app info] to ensure the notification isn't blocked.

**Comment by abhishekabhi789** [comment]
I don't fully understand your question. It sounds like the issue is with the metadata fields.

Did you edit the search parameters to get the result, or did you just proceed with the prepopulated values from PowerAmp? If you edited the metadata while searching, the issue may be related to the metadata. OR

Do you mean it sets lyrics for some songs but doesn't do anything for others, even though the lyrics are available for those tracks? The plugin might not be responding. It can post a notification if it fails to fetch lyrics, suggesting you perform a manual search. Check under the plugin settings and System > Apps > [this plugin’s app info] to ensure the notification isn't blocked.

**Comment by khebrati** [comment]
yes the second paragraph is what I meant. I did not do anything manually I just go to the lyrics part of poweramp and it fetches the lyrics, but only for 50 percent of my songs.

**Comment by khebrati** [comment]
- ![Screenshot_2024-09-18-08-41-25-711_io.github.abhishekabhi789.lyricsforpoweramp.jpg](https://github.com/user-attachments/assets/ad9b074b-768d-46be-9534-fafe01fde681)

**Comment by khebrati** [comment]
![Screenshot_2024-09-18-08-41-06-677_com.maxmpz.audioplayer.jpg](https://github.com/user-attachments/assets/813e12a3-03d8-404b-800f-82a51f6760f7)

**Comment by khebrati** [comment]
The notifications were turned off. The manual search in that failure notification does the job. Thanks! fantastic job btw

**Comment by abhishekabhi789** [comment]
Do you have any idea how it got turned off? Did you do that before, or the system did it by itself? I couldn't test the app beyond android 11, so I'm not sure how the latest android system treats this app.
